### ISSUE TITLE
Add support for 'newcap' and 'immed' options

### ISSUE THREAD

**Issue by canassa** [muhqu/jslint-plugin-for-jedit#1]
Hi!

Currently your plugin does not support the newcap and immed options:

newcap: true if Initial Caps must be used with constructor functions.
immed: true if immediate function invocations must be wrapped in parens

See: http://www.jslint.com/lint.html#options

**Comment by muhqu** [comment]
I stopped working on this plugin, as I stopped using jEdit... feel free to fork me
