### ISSUE TITLE
.jshintrc

### ISSUE THREAD

**Issue by cancerberoSgx** [muhqu/jslint-plugin-for-jedit#2]
Hi, how can I tell this plugin to use a .jshintrc file that is on a parent folder of the file that I have open ? thanks!

**Comment by muhqu** [comment]
you can't, and I'm sorry but I have discontinued developing this plugin a looooong time ago. I wonder  that jEdit is still used for JS development. You're probably a lot better served by using [Sublime Text](http://www.sublimetext.com/) or [Lighttable](http://www.lighttable.com/)...
